open Shared
open QtCore_classes
open QtGui_classes

let qWidget                        = qclass "QWidget" ~extend:qObject
let qAbstractButton                = qclass "QAbstractButton" ~extend:qWidget
let qPushButton                    = qclass "QPushButton" ~extend:qAbstractButton
let qTreeWidgetItem                = qclass "QTreeWidgetItem"
let qFileIconProvider              = qclass "QFileIconProvider"
let qTileRules                     = qclass "QTileRules"
let qItemEditorCreatorBase         = qclass "QItemEditorCreatorBase"
let qGestureRecognizer             = qclass "QGestureRecognizer"
let qTreeWidgetItemIterator        = qclass "QTreeWidgetItemIterator"
let qStyleFactory                  = qclass "QStyleFactory"
let qGraphicsLayoutItem            = qclass "QGraphicsLayoutItem"
let qItemEditorFactory             = qclass "QItemEditorFactory"
let qWhatsThis                     = qclass "QWhatsThis"
let qTableWidgetSelectionRange     = qclass "QTableWidgetSelectionRange"
let qScrollerProperties            = qclass "QScrollerProperties"
let qTableWidgetItem               = qclass "QTableWidgetItem"
let qGraphicsItem                  = qclass "QGraphicsItem"
let qToolTip                       = qclass "QToolTip"
let qListWidgetItem                = qclass "QListWidgetItem"
let qColormap                      = qclass "QColormap"
let qUndoCommand                   = qclass "QUndoCommand"
let qTextEdit'ExtraSelection = custom_type
    ~decl:"type qTextEdit'ExtraSelection = qTextCursor qt * qTextCharFormat qt"
    ~ml_pos:"qTextEdit'ExtraSelection"
    "QTextEdit::ExtraSelection"
let qTextEdit'ExtraSelection'List = custom_type
    ~ml_pos:"qTextEdit'ExtraSelection list"
    "QList<QTextEdit::ExtraSelection>"
let qFormLayout'TakeRowResult      = qclass "QFormLayout::TakeRowResult"
let qStyleHintReturn               = qclass "QStyleHintReturn"
let qLayoutItem                    = qclass "QLayoutItem"
let qStyleOption                   = qclass "QStyleOption"
let qSizePolicy                    = qclass "QSizePolicy"
let qApplication                   = qclass "QApplication" ~extend:qGuiApplication
let qKeyEventTransition            = qclass "QKeyEventTransition" ~extend:qEventTransition
let qMouseEventTransition          = qclass "QMouseEventTransition" ~extend:qEventTransition
let qFileSystemModel               = qclass "QFileSystemModel" ~extend:qAbstractItemModel
let qDirModel                      = qclass "QDirModel" ~extend:qAbstractItemModel
let qAccessibleWidget              = qclass "QAccessibleWidget" ~extend:qAccessibleObject
let qStyleOptionFocusRect          = qclass "QStyleOptionFocusRect" ~extend:qStyleOption
let qStyleOptionFrame              = qclass "QStyleOptionFrame" ~extend:qStyleOption
let qStyleOptionTabWidgetFrame     = qclass "QStyleOptionTabWidgetFrame" ~extend:qStyleOption
let qStyleOptionTabBarBase         = qclass "QStyleOptionTabBarBase" ~extend:qStyleOption
let qStyleOptionHeader             = qclass "QStyleOptionHeader" ~extend:qStyleOption
let qStyleOptionButton             = qclass "QStyleOptionButton" ~extend:qStyleOption
let qStyleOptionTab                = qclass "QStyleOptionTab" ~extend:qStyleOption
let qStyleOptionToolBar            = qclass "QStyleOptionToolBar" ~extend:qStyleOption
let qStyleOptionProgressBar        = qclass "QStyleOptionProgressBar" ~extend:qStyleOption
let qStyleOptionMenuItem           = qclass "QStyleOptionMenuItem" ~extend:qStyleOption
let qStyleOptionDockWidget         = qclass "QStyleOptionDockWidget" ~extend:qStyleOption
let qStyleOptionViewItem           = qclass "QStyleOptionViewItem" ~extend:qStyleOption
let qStyleOptionToolBox            = qclass "QStyleOptionToolBox" ~extend:qStyleOption
let qStyleOptionRubberBand         = qclass "QStyleOptionRubberBand" ~extend:qStyleOption
let qStyleOptionComplex            = qclass "QStyleOptionComplex" ~extend:qStyleOption
let qStyleOptionGraphicsItem       = qclass "QStyleOptionGraphicsItem" ~extend:qStyleOption
let qLayout                        = qclass "QLayout" ~extend:qObject
let qSpacerItem                    = qclass "QSpacerItem" ~extend:qLayoutItem
let qWidgetItem                    = qclass "QWidgetItem" ~extend:qLayoutItem
let qStyleHintReturnMask           = qclass "QStyleHintReturnMask" ~extend:qStyleHintReturn
let qStyleHintReturnVariant        = qclass "QStyleHintReturnVariant" ~extend:qStyleHintReturn
let qStylePainter                  = qclass "QStylePainter" ~extend:qPainter
let qGraphicsObject                = qclass "QGraphicsObject" ~extend:qObject
let qAbstractGraphicsShapeItem     = qclass "QAbstractGraphicsShapeItem" ~extend:qGraphicsItem
let qGraphicsLineItem              = qclass "QGraphicsLineItem" ~extend:qGraphicsItem
let qGraphicsPixmapItem            = qclass "QGraphicsPixmapItem" ~extend:qGraphicsItem
let qGraphicsItemGroup             = qclass "QGraphicsItemGroup" ~extend:qGraphicsItem
let qPlainTextDocumentLayout       = qclass "QPlainTextDocumentLayout" ~extend:qAbstractTextDocumentLayout
let qGraphicsLayout                = qclass "QGraphicsLayout" ~extend:qGraphicsLayoutItem
let qItemEditorCreator             = qclass "QItemEditorCreator" ~extend:qItemEditorCreatorBase
let qStandardItemEditorCreator     = qclass "QStandardItemEditorCreator" ~extend:qItemEditorCreatorBase
let qGraphicsSceneEvent            = qclass "QGraphicsSceneEvent" ~extend:qEvent
let qGestureEvent                  = qclass "QGestureEvent" ~extend:qEvent
let qGraphicsEffect                = qclass "QGraphicsEffect" ~extend:qObject
let qGraphicsAnchor                = qclass "QGraphicsAnchor" ~extend:qObject
let qGraphicsItemAnimation         = qclass "QGraphicsItemAnimation" ~extend:qObject
let qGraphicsScene                 = qclass "QGraphicsScene" ~extend:qObject
let qGraphicsTransform             = qclass "QGraphicsTransform" ~extend:qObject
let qAbstractItemDelegate          = qclass "QAbstractItemDelegate" ~extend:qObject
let qDataWidgetMapper              = qclass "QDataWidgetMapper" ~extend:qObject
let qAction                        = qclass "QAction" ~extend:qObject
let qActionGroup                   = qclass "QActionGroup" ~extend:qObject
let qGesture                       = qclass "QGesture" ~extend:qObject
let qShortcut                      = qclass "QShortcut" ~extend:qObject
let qStyle                         = qclass "QStyle" ~extend:qObject
let qStylePlugin                   = qclass "QStylePlugin" ~extend:qObject
let qCompleter                     = qclass "QCompleter" ~extend:qObject
let qScroller                      = qclass "QScroller" ~extend:qObject
let qSystemTrayIcon                = qclass "QSystemTrayIcon" ~extend:qObject
let qUndoGroup                     = qclass "QUndoGroup" ~extend:qObject
let qUndoStack                     = qclass "QUndoStack" ~extend:qObject
let qButtonGroup                   = qclass "QButtonGroup" ~extend:qObject
let qCommonStyle                   = qclass "QCommonStyle" ~extend:qStyle
let qPanGesture                    = qclass "QPanGesture" ~extend:qGesture
let qPinchGesture                  = qclass "QPinchGesture" ~extend:qGesture
let qSwipeGesture                  = qclass "QSwipeGesture" ~extend:qGesture
let qTapGesture                    = qclass "QTapGesture" ~extend:qGesture
let qTapAndHoldGesture             = qclass "QTapAndHoldGesture" ~extend:qGesture
let qWidgetAction                  = qclass "QWidgetAction" ~extend:qAction
let qItemDelegate                  = qclass "QItemDelegate" ~extend:qAbstractItemDelegate
let qStyledItemDelegate            = qclass "QStyledItemDelegate" ~extend:qAbstractItemDelegate
let qGraphicsScale                 = qclass "QGraphicsScale" ~extend:qGraphicsTransform
let qGraphicsRotation              = qclass "QGraphicsRotation" ~extend:qGraphicsTransform
let qGraphicsColorizeEffect        = qclass "QGraphicsColorizeEffect" ~extend:qGraphicsEffect
let qGraphicsBlurEffect            = qclass "QGraphicsBlurEffect" ~extend:qGraphicsEffect
let qGraphicsDropShadowEffect      = qclass "QGraphicsDropShadowEffect" ~extend:qGraphicsEffect
let qGraphicsOpacityEffect         = qclass "QGraphicsOpacityEffect" ~extend:qGraphicsEffect
let qGraphicsSceneMouseEvent       = qclass "QGraphicsSceneMouseEvent" ~extend:qGraphicsSceneEvent
let qGraphicsSceneWheelEvent       = qclass "QGraphicsSceneWheelEvent" ~extend:qGraphicsSceneEvent
let qGraphicsSceneContextMenuEvent = qclass "QGraphicsSceneContextMenuEvent" ~extend:qGraphicsSceneEvent
let qGraphicsSceneHoverEvent       = qclass "QGraphicsSceneHoverEvent" ~extend:qGraphicsSceneEvent
let qGraphicsSceneHelpEvent        = qclass "QGraphicsSceneHelpEvent" ~extend:qGraphicsSceneEvent
let qGraphicsSceneDragDropEvent    = qclass "QGraphicsSceneDragDropEvent" ~extend:qGraphicsSceneEvent
let qGraphicsSceneResizeEvent      = qclass "QGraphicsSceneResizeEvent" ~extend:qGraphicsSceneEvent
let qGraphicsSceneMoveEvent        = qclass "QGraphicsSceneMoveEvent" ~extend:qGraphicsSceneEvent
let qGraphicsAnchorLayout          = qclass "QGraphicsAnchorLayout" ~extend:qGraphicsLayout
let qGraphicsGridLayout            = qclass "QGraphicsGridLayout" ~extend:qGraphicsLayout
let qGraphicsLinearLayout          = qclass "QGraphicsLinearLayout" ~extend:qGraphicsLayout
let qGraphicsPathItem              = qclass "QGraphicsPathItem" ~extend:qAbstractGraphicsShapeItem
let qGraphicsRectItem              = qclass "QGraphicsRectItem" ~extend:qAbstractGraphicsShapeItem
let qGraphicsEllipseItem           = qclass "QGraphicsEllipseItem" ~extend:qAbstractGraphicsShapeItem
let qGraphicsPolygonItem           = qclass "QGraphicsPolygonItem" ~extend:qAbstractGraphicsShapeItem
let qGraphicsSimpleTextItem        = qclass "QGraphicsSimpleTextItem" ~extend:qAbstractGraphicsShapeItem
let qGraphicsTextItem              = qclass "QGraphicsTextItem" ~extend:qGraphicsObject
let qGraphicsWidget                = qclass "QGraphicsWidget" ~extend:qGraphicsObject
let qDialog                        = qclass "QDialog" ~extend:qWidget
let qWizardPage                    = qclass "QWizardPage" ~extend:qWidget
let qDesktopWidget                 = qclass "QDesktopWidget" ~extend:qWidget
let qOpenGLWidget                  = qclass "QOpenGLWidget" ~extend:qWidget
let qAbstractSlider                = qclass "QAbstractSlider" ~extend:qWidget
let qAbstractSpinBox               = qclass "QAbstractSpinBox" ~extend:qWidget
let qCalendarWidget                = qclass "QCalendarWidget" ~extend:qWidget
let qComboBox                      = qclass "QComboBox" ~extend:qWidget
let qDialogButtonBox               = qclass "QDialogButtonBox" ~extend:qWidget
let qDockWidget                    = qclass "QDockWidget" ~extend:qWidget
let qFocusFrame                    = qclass "QFocusFrame" ~extend:qWidget
let qFrame                         = qclass "QFrame" ~extend:qWidget
let qGroupBox                      = qclass "QGroupBox" ~extend:qWidget
let qKeySequenceEdit               = qclass "QKeySequenceEdit" ~extend:qWidget
let qLineEdit                      = qclass "QLineEdit" ~extend:qWidget
(*let qMacCocoaViewContainer         = qclass "QMacCocoaViewContainer" ~extend:qWidget*)
(*let qMacNativeWidget               = qclass "QMacNativeWidget" ~extend:qWidget*)
let qMainWindow                    = qclass "QMainWindow" ~extend:qWidget
let qMdiSubWindow                  = qclass "QMdiSubWindow" ~extend:qWidget
let qMenu                          = qclass "QMenu" ~extend:qWidget
let qMenuBar                       = qclass "QMenuBar" ~extend:qWidget
let qProgressBar                   = qclass "QProgressBar" ~extend:qWidget
let qRubberBand                    = qclass "QRubberBand" ~extend:qWidget
let qSizeGrip                      = qclass "QSizeGrip" ~extend:qWidget
let qSplashScreen                  = qclass "QSplashScreen" ~extend:qWidget
let qSplitterHandle                = qclass "QSplitterHandle" ~extend:qWidget
let qStatusBar                     = qclass "QStatusBar" ~extend:qWidget
let qTabBar                        = qclass "QTabBar" ~extend:qWidget
let qTabWidget                     = qclass "QTabWidget" ~extend:qWidget
let qToolBar                       = qclass "QToolBar" ~extend:qWidget
let qBoxLayout                     = qclass "QBoxLayout" ~extend:qLayout
let qFormLayout                    = qclass "QFormLayout" ~extend:qLayout
let qGridLayout                    = qclass "QGridLayout" ~extend:qLayout
let qStackedLayout                 = qclass "QStackedLayout" ~extend:qLayout
let qStyleOptionSlider             = qclass "QStyleOptionSlider" ~extend:qStyleOptionComplex
let qStyleOptionSpinBox            = qclass "QStyleOptionSpinBox" ~extend:qStyleOptionComplex
let qStyleOptionToolButton         = qclass "QStyleOptionToolButton" ~extend:qStyleOptionComplex
let qStyleOptionComboBox           = qclass "QStyleOptionComboBox" ~extend:qStyleOptionComplex
let qStyleOptionTitleBar           = qclass "QStyleOptionTitleBar" ~extend:qStyleOptionComplex
let qStyleOptionGroupBox           = qclass "QStyleOptionGroupBox" ~extend:qStyleOptionComplex
let qStyleOptionSizeGrip           = qclass "QStyleOptionSizeGrip" ~extend:qStyleOptionComplex
let qHBoxLayout                    = qclass "QHBoxLayout" ~extend:qBoxLayout
let qVBoxLayout                    = qclass "QVBoxLayout" ~extend:qBoxLayout
let qAbstractScrollArea            = qclass "QAbstractScrollArea" ~extend:qFrame
let qLabel                         = qclass "QLabel" ~extend:qFrame
let qLCDNumber                     = qclass "QLCDNumber" ~extend:qFrame
let qSplitter                      = qclass "QSplitter" ~extend:qFrame
let qStackedWidget                 = qclass "QStackedWidget" ~extend:qFrame
let qToolBox                       = qclass "QToolBox" ~extend:qFrame
let qFontComboBox                  = qclass "QFontComboBox" ~extend:qComboBox
let qDateTimeEdit                  = qclass "QDateTimeEdit" ~extend:qAbstractSpinBox
let qSpinBox                       = qclass "QSpinBox" ~extend:qAbstractSpinBox
let qDoubleSpinBox                 = qclass "QDoubleSpinBox" ~extend:qAbstractSpinBox
let qDial                          = qclass "QDial" ~extend:qAbstractSlider
let qScrollBar                     = qclass "QScrollBar" ~extend:qAbstractSlider
let qSlider                        = qclass "QSlider" ~extend:qAbstractSlider
let qCheckBox                      = qclass "QCheckBox" ~extend:qAbstractButton
let qRadioButton                   = qclass "QRadioButton" ~extend:qAbstractButton
let qToolButton                    = qclass "QToolButton" ~extend:qAbstractButton
let qColorDialog                   = qclass "QColorDialog" ~extend:qDialog
let qErrorMessage                  = qclass "QErrorMessage" ~extend:qDialog
let qFileDialog                    = qclass "QFileDialog" ~extend:qDialog
let qFontDialog                    = qclass "QFontDialog" ~extend:qDialog
let qInputDialog                   = qclass "QInputDialog" ~extend:qDialog
let qMessageBox                    = qclass "QMessageBox" ~extend:qDialog
let qProgressDialog                = qclass "QProgressDialog" ~extend:qDialog
let qWizard                        = qclass "QWizard" ~extend:qDialog
let qGraphicsProxyWidget           = qclass "QGraphicsProxyWidget" ~extend:qGraphicsWidget
let qProxyStyle                    = qclass "QProxyStyle" ~extend:qCommonStyle
let qCommandLinkButton             = qclass "QCommandLinkButton" ~extend:qPushButton
let qTimeEdit                      = qclass "QTimeEdit" ~extend:qDateTimeEdit
let qDateEdit                      = qclass "QDateEdit" ~extend:qDateTimeEdit
let qGraphicsView                  = qclass "QGraphicsView" ~extend:qAbstractScrollArea
let qAbstractItemView              = qclass "QAbstractItemView" ~extend:qAbstractScrollArea
let qMdiArea                       = qclass "QMdiArea" ~extend:qAbstractScrollArea
let qPlainTextEdit                 = qclass "QPlainTextEdit" ~extend:qAbstractScrollArea
let qScrollArea                    = qclass "QScrollArea" ~extend:qAbstractScrollArea
let qTextEdit                      = qclass "QTextEdit" ~extend:qAbstractScrollArea
let qTextBrowser                   = qclass "QTextBrowser" ~extend:qTextEdit
let qColumnView                    = qclass "QColumnView" ~extend:qAbstractItemView
let qHeaderView                    = qclass "QHeaderView" ~extend:qAbstractItemView
let qListView                      = qclass "QListView" ~extend:qAbstractItemView
let qTableView                     = qclass "QTableView" ~extend:qAbstractItemView
let qTreeView                      = qclass "QTreeView" ~extend:qAbstractItemView
let qTreeWidget                    = qclass "QTreeWidget" ~extend:qTreeView
let qTableWidget                   = qclass "QTableWidget" ~extend:qTableView
let qListWidget                    = qclass "QListWidget" ~extend:qListView
let qUndoView                      = qclass "QUndoView" ~extend:qListView
