open Mlspec.Decl
open QtCore_classes
open QtGui_classes

let qWidget                        = qextends "QWidget" qObject
let qAbstractButton                = qextends "QAbstractButton" qWidget
let qPushButton                    = qextends "QPushButton" qAbstractButton
let qTreeWidgetItem                = qclass "QTreeWidgetItem"
let qFileIconProvider              = qclass "QFileIconProvider"
let qTileRules                     = qclass "QTileRules"
let qItemEditorCreatorBase         = qclass "QItemEditorCreatorBase"
let qGestureRecognizer             = qclass "QGestureRecognizer"
let qTreeWidgetItemIterator        = qclass "QTreeWidgetItemIterator"
let qStyleFactory                  = qclass "QStyleFactory"
let qGraphicsLayoutItem            = qclass "QGraphicsLayoutItem"
let qItemEditorFactory             = qclass "QItemEditorFactory"
let qWhatsThis                     = qclass "QWhatsThis"
let qTableWidgetSelectionRange     = qclass "QTableWidgetSelectionRange"
let qScrollerProperties            = qclass "QScrollerProperties"
let qTableWidgetItem               = qclass "QTableWidgetItem"
let qGraphicsItem                  = qclass "QGraphicsItem"
let qToolTip                       = qclass "QToolTip"
let qListWidgetItem                = qclass "QListWidgetItem"
let qColormap                      = qclass "QColormap"
let qUndoCommand                   = qclass "QUndoCommand"
let qTextEdit'ExtraSelection = custom_type
    ~ml_decl:"type qTextEdit'ExtraSelection = qTextCursor qt * qTextCharFormat qt"
    ~ml_name:"qTextEdit'ExtraSelection"
    "QTextEdit::ExtraSelection"
let qTextEdit'ExtraSelection'List = custom_type
    ~ml_name:"qTextEdit'ExtraSelection list"
    "QList<QTextEdit::ExtraSelection>"
let qFormLayout'TakeRowResult      = qclass "QFormLayout::TakeRowResult"
let qStyleHintReturn               = qclass "QStyleHintReturn"
let qLayoutItem                    = qclass "QLayoutItem"
let qStyleOption                   = qclass "QStyleOption"
let qSizePolicy                    = qclass "QSizePolicy"
let qApplication                   = qextends "QApplication" qGuiApplication
let qKeyEventTransition            = qextends "QKeyEventTransition" qEventTransition
let qMouseEventTransition          = qextends "QMouseEventTransition" qEventTransition
let qFileSystemModel               = qextends "QFileSystemModel" qAbstractItemModel
let qDirModel                      = qextends "QDirModel" qAbstractItemModel
let qAccessibleWidget              = qextends "QAccessibleWidget" qAccessibleObject
let qStyleOptionFocusRect          = qextends "QStyleOptionFocusRect" qStyleOption
let qStyleOptionFrame              = qextends "QStyleOptionFrame" qStyleOption
let qStyleOptionTabWidgetFrame     = qextends "QStyleOptionTabWidgetFrame" qStyleOption
let qStyleOptionTabBarBase         = qextends "QStyleOptionTabBarBase" qStyleOption
let qStyleOptionHeader             = qextends "QStyleOptionHeader" qStyleOption
let qStyleOptionButton             = qextends "QStyleOptionButton" qStyleOption
let qStyleOptionTab                = qextends "QStyleOptionTab" qStyleOption
let qStyleOptionToolBar            = qextends "QStyleOptionToolBar" qStyleOption
let qStyleOptionProgressBar        = qextends "QStyleOptionProgressBar" qStyleOption
let qStyleOptionMenuItem           = qextends "QStyleOptionMenuItem" qStyleOption
let qStyleOptionDockWidget         = qextends "QStyleOptionDockWidget" qStyleOption
let qStyleOptionViewItem           = qextends "QStyleOptionViewItem" qStyleOption
let qStyleOptionToolBox            = qextends "QStyleOptionToolBox" qStyleOption
let qStyleOptionRubberBand         = qextends "QStyleOptionRubberBand" qStyleOption
let qStyleOptionComplex            = qextends "QStyleOptionComplex" qStyleOption
let qStyleOptionGraphicsItem       = qextends "QStyleOptionGraphicsItem" qStyleOption
let qLayout                        = qextends "QLayout" qObject
let qSpacerItem                    = qextends "QSpacerItem" qLayoutItem
let qWidgetItem                    = qextends "QWidgetItem" qLayoutItem
let qStyleHintReturnMask           = qextends "QStyleHintReturnMask" qStyleHintReturn
let qStyleHintReturnVariant        = qextends "QStyleHintReturnVariant" qStyleHintReturn
let qStylePainter                  = qextends "QStylePainter" qPainter
let qGraphicsObject                = qextends "QGraphicsObject" qObject
let qAbstractGraphicsShapeItem     = qextends "QAbstractGraphicsShapeItem" qGraphicsItem
let qGraphicsLineItem              = qextends "QGraphicsLineItem" qGraphicsItem
let qGraphicsPixmapItem            = qextends "QGraphicsPixmapItem" qGraphicsItem
let qGraphicsItemGroup             = qextends "QGraphicsItemGroup" qGraphicsItem
let qPlainTextDocumentLayout       = qextends "QPlainTextDocumentLayout" qAbstractTextDocumentLayout
let qGraphicsLayout                = qextends "QGraphicsLayout" qGraphicsLayoutItem
let qItemEditorCreator             = qextends "QItemEditorCreator" qItemEditorCreatorBase
let qStandardItemEditorCreator     = qextends "QStandardItemEditorCreator" qItemEditorCreatorBase
let qGraphicsSceneEvent            = qextends "QGraphicsSceneEvent" qEvent
let qGestureEvent                  = qextends "QGestureEvent" qEvent
let qGraphicsEffect                = qextends "QGraphicsEffect" qObject
let qGraphicsAnchor                = qextends "QGraphicsAnchor" qObject
let qGraphicsItemAnimation         = qextends "QGraphicsItemAnimation" qObject
let qGraphicsScene                 = qextends "QGraphicsScene" qObject
let qGraphicsTransform             = qextends "QGraphicsTransform" qObject
let qAbstractItemDelegate          = qextends "QAbstractItemDelegate" qObject
let qDataWidgetMapper              = qextends "QDataWidgetMapper" qObject
let qAction                        = qextends "QAction" qObject
let qActionGroup                   = qextends "QActionGroup" qObject
let qGesture                       = qextends "QGesture" qObject
let qShortcut                      = qextends "QShortcut" qObject
let qStyle                         = qextends "QStyle" qObject
let qStylePlugin                   = qextends "QStylePlugin" qObject
let qCompleter                     = qextends "QCompleter" qObject
let qScroller                      = qextends "QScroller" qObject
let qSystemTrayIcon                = qextends "QSystemTrayIcon" qObject
let qUndoGroup                     = qextends "QUndoGroup" qObject
let qUndoStack                     = qextends "QUndoStack" qObject
let qButtonGroup                   = qextends "QButtonGroup" qObject
let qCommonStyle                   = qextends "QCommonStyle" qStyle
let qPanGesture                    = qextends "QPanGesture" qGesture
let qPinchGesture                  = qextends "QPinchGesture" qGesture
let qSwipeGesture                  = qextends "QSwipeGesture" qGesture
let qTapGesture                    = qextends "QTapGesture" qGesture
let qTapAndHoldGesture             = qextends "QTapAndHoldGesture" qGesture
let qWidgetAction                  = qextends "QWidgetAction" qAction
let qItemDelegate                  = qextends "QItemDelegate" qAbstractItemDelegate
let qStyledItemDelegate            = qextends "QStyledItemDelegate" qAbstractItemDelegate
let qGraphicsScale                 = qextends "QGraphicsScale" qGraphicsTransform
let qGraphicsRotation              = qextends "QGraphicsRotation" qGraphicsTransform
let qGraphicsColorizeEffect        = qextends "QGraphicsColorizeEffect" qGraphicsEffect
let qGraphicsBlurEffect            = qextends "QGraphicsBlurEffect" qGraphicsEffect
let qGraphicsDropShadowEffect      = qextends "QGraphicsDropShadowEffect" qGraphicsEffect
let qGraphicsOpacityEffect         = qextends "QGraphicsOpacityEffect" qGraphicsEffect
let qGraphicsSceneMouseEvent       = qextends "QGraphicsSceneMouseEvent" qGraphicsSceneEvent
let qGraphicsSceneWheelEvent       = qextends "QGraphicsSceneWheelEvent" qGraphicsSceneEvent
let qGraphicsSceneContextMenuEvent = qextends "QGraphicsSceneContextMenuEvent" qGraphicsSceneEvent
let qGraphicsSceneHoverEvent       = qextends "QGraphicsSceneHoverEvent" qGraphicsSceneEvent
let qGraphicsSceneHelpEvent        = qextends "QGraphicsSceneHelpEvent" qGraphicsSceneEvent
let qGraphicsSceneDragDropEvent    = qextends "QGraphicsSceneDragDropEvent" qGraphicsSceneEvent
let qGraphicsSceneResizeEvent      = qextends "QGraphicsSceneResizeEvent" qGraphicsSceneEvent
let qGraphicsSceneMoveEvent        = qextends "QGraphicsSceneMoveEvent" qGraphicsSceneEvent
let qGraphicsAnchorLayout          = qextends "QGraphicsAnchorLayout" qGraphicsLayout
let qGraphicsGridLayout            = qextends "QGraphicsGridLayout" qGraphicsLayout
let qGraphicsLinearLayout          = qextends "QGraphicsLinearLayout" qGraphicsLayout
let qGraphicsPathItem              = qextends "QGraphicsPathItem" qAbstractGraphicsShapeItem
let qGraphicsRectItem              = qextends "QGraphicsRectItem" qAbstractGraphicsShapeItem
let qGraphicsEllipseItem           = qextends "QGraphicsEllipseItem" qAbstractGraphicsShapeItem
let qGraphicsPolygonItem           = qextends "QGraphicsPolygonItem" qAbstractGraphicsShapeItem
let qGraphicsSimpleTextItem        = qextends "QGraphicsSimpleTextItem" qAbstractGraphicsShapeItem
let qGraphicsTextItem              = qextends "QGraphicsTextItem" qGraphicsObject
let qGraphicsWidget                = qextends "QGraphicsWidget" qGraphicsObject
let qDialog                        = qextends "QDialog" qWidget
let qWizardPage                    = qextends "QWizardPage" qWidget
let qDesktopWidget                 = qextends "QDesktopWidget" qWidget
let qOpenGLWidget                  = qextends "QOpenGLWidget" qWidget
let qAbstractSlider                = qextends "QAbstractSlider" qWidget
let qAbstractSpinBox               = qextends "QAbstractSpinBox" qWidget
let qCalendarWidget                = qextends "QCalendarWidget" qWidget
let qComboBox                      = qextends "QComboBox" qWidget
let qDialogButtonBox               = qextends "QDialogButtonBox" qWidget
let qDockWidget                    = qextends "QDockWidget" qWidget
let qFocusFrame                    = qextends "QFocusFrame" qWidget
let qFrame                         = qextends "QFrame" qWidget
let qGroupBox                      = qextends "QGroupBox" qWidget
let qKeySequenceEdit               = qextends "QKeySequenceEdit" qWidget
let qLineEdit                      = qextends "QLineEdit" qWidget
(*let qMacCocoaViewContainer         = qextends "QMacCocoaViewContainer" qWidget*)
(*let qMacNativeWidget               = qextends "QMacNativeWidget" qWidget*)
let qMainWindow                    = qextends "QMainWindow" qWidget
let qMdiSubWindow                  = qextends "QMdiSubWindow" qWidget
let qMenu                          = qextends "QMenu" qWidget
let qMenuBar                       = qextends "QMenuBar" qWidget
let qProgressBar                   = qextends "QProgressBar" qWidget
let qRubberBand                    = qextends "QRubberBand" qWidget
let qSizeGrip                      = qextends "QSizeGrip" qWidget
let qSplashScreen                  = qextends "QSplashScreen" qWidget
let qSplitterHandle                = qextends "QSplitterHandle" qWidget
let qStatusBar                     = qextends "QStatusBar" qWidget
let qTabBar                        = qextends "QTabBar" qWidget
let qTabWidget                     = qextends "QTabWidget" qWidget
let qToolBar                       = qextends "QToolBar" qWidget
let qBoxLayout                     = qextends "QBoxLayout" qLayout
let qFormLayout                    = qextends "QFormLayout" qLayout
let qGridLayout                    = qextends "QGridLayout" qLayout
let qStackedLayout                 = qextends "QStackedLayout" qLayout
let qStyleOptionSlider             = qextends "QStyleOptionSlider" qStyleOptionComplex
let qStyleOptionSpinBox            = qextends "QStyleOptionSpinBox" qStyleOptionComplex
let qStyleOptionToolButton         = qextends "QStyleOptionToolButton" qStyleOptionComplex
let qStyleOptionComboBox           = qextends "QStyleOptionComboBox" qStyleOptionComplex
let qStyleOptionTitleBar           = qextends "QStyleOptionTitleBar" qStyleOptionComplex
let qStyleOptionGroupBox           = qextends "QStyleOptionGroupBox" qStyleOptionComplex
let qStyleOptionSizeGrip           = qextends "QStyleOptionSizeGrip" qStyleOptionComplex
let qHBoxLayout                    = qextends "QHBoxLayout" qBoxLayout
let qVBoxLayout                    = qextends "QVBoxLayout" qBoxLayout
let qAbstractScrollArea            = qextends "QAbstractScrollArea" qFrame
let qLabel                         = qextends "QLabel" qFrame
let qLCDNumber                     = qextends "QLCDNumber" qFrame
let qSplitter                      = qextends "QSplitter" qFrame
let qStackedWidget                 = qextends "QStackedWidget" qFrame
let qToolBox                       = qextends "QToolBox" qFrame
let qFontComboBox                  = qextends "QFontComboBox" qComboBox
let qDateTimeEdit                  = qextends "QDateTimeEdit" qAbstractSpinBox
let qSpinBox                       = qextends "QSpinBox" qAbstractSpinBox
let qDoubleSpinBox                 = qextends "QDoubleSpinBox" qAbstractSpinBox
let qDial                          = qextends "QDial" qAbstractSlider
let qScrollBar                     = qextends "QScrollBar" qAbstractSlider
let qSlider                        = qextends "QSlider" qAbstractSlider
let qCheckBox                      = qextends "QCheckBox" qAbstractButton
let qRadioButton                   = qextends "QRadioButton" qAbstractButton
let qToolButton                    = qextends "QToolButton" qAbstractButton
let qColorDialog                   = qextends "QColorDialog" qDialog
let qErrorMessage                  = qextends "QErrorMessage" qDialog
let qFileDialog                    = qextends "QFileDialog" qDialog
let qFontDialog                    = qextends "QFontDialog" qDialog
let qInputDialog                   = qextends "QInputDialog" qDialog
let qMessageBox                    = qextends "QMessageBox" qDialog
let qProgressDialog                = qextends "QProgressDialog" qDialog
let qWizard                        = qextends "QWizard" qDialog
let qGraphicsProxyWidget           = qextends "QGraphicsProxyWidget" qGraphicsWidget
let qProxyStyle                    = qextends "QProxyStyle" qCommonStyle
let qCommandLinkButton             = qextends "QCommandLinkButton" qPushButton
let qTimeEdit                      = qextends "QTimeEdit" qDateTimeEdit
let qDateEdit                      = qextends "QDateEdit" qDateTimeEdit
let qGraphicsView                  = qextends "QGraphicsView" qAbstractScrollArea
let qAbstractItemView              = qextends "QAbstractItemView" qAbstractScrollArea
let qMdiArea                       = qextends "QMdiArea" qAbstractScrollArea
let qPlainTextEdit                 = qextends "QPlainTextEdit" qAbstractScrollArea
let qScrollArea                    = qextends "QScrollArea" qAbstractScrollArea
let qTextEdit                      = qextends "QTextEdit" qAbstractScrollArea
let qTextBrowser                   = qextends "QTextBrowser" qTextEdit
let qColumnView                    = qextends "QColumnView" qAbstractItemView
let qHeaderView                    = qextends "QHeaderView" qAbstractItemView
let qListView                      = qextends "QListView" qAbstractItemView
let qTableView                     = qextends "QTableView" qAbstractItemView
let qTreeView                      = qextends "QTreeView" qAbstractItemView
let qTreeWidget                    = qextends "QTreeWidget" qTreeView
let qTableWidget                   = qextends "QTableWidget" qTableView
let qListWidget                    = qextends "QListWidget" qListView
let qUndoView                      = qextends "QUndoView" qListView
